=== Osbern/ISTIC_M2GL/AddressBook.dbunit/data/dataset.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dataset (ADDRESS+)>
<!ELEMENT ADDRESS EMPTY>
<!ATTLIST ADDRESS
    LASTNAME CDATA #IMPLIED
    FIRSTNAME CDATA #IMPLIED
    MIDDLENAME CDATA #IMPLIED
    PHONE CDATA #IMPLIED
    EMAIL CDATA #IMPLIED
    ADDRESS1 CDATA #IMPLIED
    ADDRESS2 CDATA #IMPLIED
    CITY CDATA #IMPLIED
    STATE CDATA #IMPLIED
    POSTALCODE CDATA #IMPLIED
    COUNTRY CDATA #IMPLIED
>

=== Osbern/ISTIC_M2GL/AddressBook.dbunit/data/dataset15addresses.xml
<!DOCTYPE dataset SYSTEM "data/dataset.dtd">
<dataset>
    <ADDRESS LASTNAME="CADAVID"
    	FIRSTNAME="Juan"
    	MIDDLENAME="Jose"
    	PHONE="5742554391"
    	EMAIL="Juan.Cadavid@inria.fr"
    	ADDRESS1="11 Place du Colombier"
    	ADDRESS2="Ap 7"
    	CITY="Rennes"
    	STATE="Bretagne"
    	POSTALCODE="35000"
    	COUNTRY="France"
    	/> 
    <ADDRESS LASTNAME="Jezequel"
    	FIRSTNAME="Jean"
    	MIDDLENAME="Marc"
    	PHONE="02998478632"
    	EMAIL="Juan.Cadavid@inria.fr"
    	ADDRESS1="9 Rue de Paris"
    	ADDRESS2="Porte 3"
    	CITY="Rennes"
    	STATE="Bretagne"
    	POSTALCODE="35000"
    	COUNTRY="France"
    	/> 
    <ADDRESS LASTNAME="Moha"
    	FIRSTNAME="Naouel"
    	MIDDLENAME="Marie"
    	PHONE="02998478678"
    	EMAIL="Naouel.Moha@inria.fr"
    	ADDRESS1="265 Rue de Saint Malo"
    	ADDRESS2="Ap 135"
    	CITY="Rennes"
    	STATE="Bretagne"
    	POSTALCODE="35100"
    	COUNTRY="France"
    	/> 
    <ADDRESS LASTNAME="Blouin"
    	FIRSTNAME="Arnauld"
    	MIDDLENAME="Antoine"
    	PHONE="0299847865"
    	EMAIL="Arnauld.Blouin@inria.fr"
    	ADDRESS1="89 rue de Rennes"
    	ADDRESS2="Ap 72"
    	CITY="Cesson-Sevigné"
    	STATE="Bretagne"
    	POSTALCODE="35000"
    	COUNTRY="France"
    	/> 
    <ADDRESS LASTNAME="Clevreul"
    	FIRSTNAME="Louis"
    	MIDDLENAME="Robert"
    	PHONE="0299842598"
    	EMAIL="Louis.Clevreul@inria.fr"
    	ADDRESS1="74 Rue de Rivoli"
    	ADDRESS2="Porte 1"
    	CITY="Paris"
    	STATE="Ille de France"
    	POSTALCODE="75008"
    	COUNTRY="France"
    	/> 
    <ADDRESS LASTNAME="Bouthemy"
    	FIRSTNAME="Patrice"
    	MIDDLENAME="Pierre"
    	PHONE="0299841565"
    	EMAIL="Patrice.Bouthemy@inria.fr"
    	ADDRESS1="4 Place Hoche"
    	ADDRESS2="Etage 1"
    	CITY="Rennes"
    	STATE="Bretagne"
    	POSTALCODE="35000"
    	COUNTRY="France"
    	/> 
    <ADDRESS LASTNAME="Nain"
    	FIRSTNAME="Gregoire"
    	MIDDLENAME="Joseph"
    	PHONE="0299842563"
    	EMAIL="Gregoire.Nain@inria.fr"
    	ADDRESS1="13 Rue St Helier"
    	ADDRESS2="Porte 3"
    	CITY="Rennes"
    	STATE="Bretagne"
    	POSTALCODE="35005"
    	COUNTRY="France"
    	/> 
    <ADDRESS LASTNAME="Morin"
    	FIRSTNAME="Candice"
    	MIDDLENAME="Veronique"
    	PHONE="02998478632"
    	EMAIL="Candice.Morin@inria.fr"
    	ADDRESS1="74 rue des ormeaux"
    	ADDRESS2="Ap 7"
    	CITY="Chantepie"
    	STATE="Bretagne"
    	POSTALCODE="35050"
    	COUNTRY="France"
    	></ADDRESS> 
    <ADDRESS LASTNAME="Boscaino"
    	FIRSTNAME="Roxanne"
    	MIDDLENAME="Claudie"
    	PHONE="0299845490"
    	EMAIL="Roxanne.Boscaino@inria.fr"
    	ADDRESS1="43 Rue du Pre"
    	ADDRESS2="Porte 8"
    	CITY="Rennes"
    	STATE="Bretagne"
    	POSTALCODE="35000"
    	COUNTRY="France"
    	/> 
    <ADDRESS LASTNAME="Domeneci"
    	FIRSTNAME="Michelle"
    	MIDDLENAME="Sandro"
    	PHONE="08998478632"
    	EMAIL="Michelle.Domeneci@inria.it"
    	ADDRESS1="11 "
    	ADDRESS2="Ap 7"
    	CITY="Cagliari"
    	STATE="Sardegne"
    	POSTALCODE="35000"
    	COUNTRY="Italy"
    	/> 
    <ADDRESS LASTNAME="Verdun"
    	FIRSTNAME="Pierrette"
    	MIDDLENAME="Charlotte"
    	PHONE="0299841699"
    	EMAIL="Pierrette.Charlotte@inria.fr"
    	ADDRESS1="8 Rue Saint-Michel"
    	ADDRESS2="Etage 6"
    	CITY="Rennes"
    	STATE="Bretagne"
    	POSTALCODE="35000"
    	COUNTRY="France"
    	/> 
    <ADDRESS LASTNAME="Cathelineau"
    	FIRSTNAME="Jean"
    	MIDDLENAME="Philippe"
    	PHONE="0299841236"
    	EMAIL="Jean.Cathelineau@inria.fr"
    	ADDRESS1="86 Rue St Helier"
    	ADDRESS2="Porte 21"
    	CITY="Vannes"
    	STATE="Morbihan"
    	POSTALCODE="56021"
    	COUNTRY="France"
    	/> 
    <ADDRESS LASTNAME="Chirac"
    	FIRSTNAME="Jacques"
    	MIDDLENAME="André"
    	PHONE="02998471299"
    	EMAIL="Jacques.Chirac@inria.fr"
    	ADDRESS1="2 Palais de l'Elysee"
    	ADDRESS2="Porte 1"
    	CITY="Paris"
    	STATE="Ille de France"
    	POSTALCODE="75001"
    	COUNTRY="France"
    	></ADDRESS> 
    <ADDRESS LASTNAME="Lavernne"
    	FIRSTNAME="Pierre"
    	MIDDLENAME="Emeric"
    	PHONE="0299848817"
    	EMAIL="Roxanne.Boscaino@inria.fr"
    	ADDRESS1="43 Rue du Pre"
    	ADDRESS2="Porte 8"
    	CITY="Rennes"
    	STATE="Bretagne"
    	POSTALCODE="35000"
    	COUNTRY="France"
    	/> 
    <ADDRESS LASTNAME="Brun"
    	FIRSTNAME="Cedric"
    	MIDDLENAME="Marie"
    	PHONE="08998475561"
    	EMAIL="Cedric.Brun@inria.it"
    	ADDRESS1="11 "
    	ADDRESS2="Ap 7"
    	CITY="Nantes"
    	STATE="Pays de la Loire"
    	POSTALCODE="44000"
    	COUNTRY="France"
    	/> 
</dataset>
